# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main
stages:
 - stage: Build
   displayName: Create build artifact
   jobs:
     - job: BuildArtifact
       pool: MyLaptop
       steps:
         - task: UiPathPack@2
           inputs:
             versionType: 'AutoVersion'
             projectJsonPath: '$(Build.SourcesDirectory)'
             outputType: 'Process'
             orchestratorConnection: 'UiPathCiCDPipeline'
             outputPath: '$(Build.ArtifactStagingDirectory)'
         - task: UiPathDeploy@2
           inputs:
            orchestratorConnection: 'UiPathCiCDPipeline'
            packagesPath: '$(Build.SourcesDirectory)'
            folderName: 'Default'    