# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main
variables:
  - group: UiPath 
stages:
 - stage: Build
   displayName: Create build artifact
   jobs:
     - job: BuildArtifact
       pool: MyLaptop
       steps:
         - task: "PowerShell@2"
           inputs:              
            script: 'Import-Module UiPath.Powershell;$token = Get-UiPathAuthToken -ClientId $(DevClientID) -UserKey $(DevUserKey) -AccountName $(DevUserKey) -CloudDeployment ‘Production’ -TenantName $(DevClientID);Add-UiPathPackage -PackageFile $(Pipeline.Workspace)\TestCases.1.0.$(Build.BuildNumber).nupkg -AuthToken $token'
